services:
  auth-backend:
    build: ./AuthFastAPI
    container_name: auth-backend
    restart: unless-stopped
    ports:
      - "1515:1515"
    volumes:
      - ./media:/usr/src/app/media
    networks:
      - hotels_network
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
    depends_on:
      - postgres-db
    command: >
      bash -c "uvicorn main:app --reload --host 0.0.0.0 --port 1515"

  django-backend:
    build: ./Rental-Django
    container_name: django-backend
    restart: unless-stopped
    ports:
      - "1212:1212"
    volumes:
      - ./media:/usr/src/app/media
    networks:
      - hotels_network
    env_file:
      - .env
    environment:
      DATABASE_URL:  "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
      DJANGO_SECRET_KEY: "$${SECRET_KEY}"
      DJANGO_DEBUG: "$${DEBUG}"
    depends_on:
      postgres-db:
        condition: service_healthy
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn --bind 0.0.0.0:1212 config.wsgi:application"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - django-backend
      - auth-backend
    networks:
      - hotels_network
    env_file:
      - .env

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost"]
      interval: 5s
      retries: 5
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hotels_network


volumes:
  django_media_volume:
  postgres_data:

networks:
  hotels_network:
    external: true
